### ISSUE TITLE
Do we need to adjust the Tomcat Memory in the OpenMRS docker container?

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/docker-builds#3]
Hi,

It's common practice in OpenMRS to set the runtime environment variable for tomcat7. Should we add a line into Docker Compose? [Here's the script I run](https://gist.github.com/craigappl/6e54abfb8a59c5a28a63d2a6179cd506#file-openmrs-platform-1-11-x-ubuntu14-04-install-sh-L24).

**Comment by maina** [comment]
Yes

**Comment by craigappl** [comment]
Thanks, I'll create a PR.

**Comment by keymane** [comment]
@craigappl Closing this issue.

We've adjusted the tomcat memory 
https://github.com/OpenSRP/docker-builds/blob/master/Dockerfile#L418 
https://github.com/OpenSRP/docker-builds/blob/master/composed/Dockerfile#L76 
https://github.com/OpenSRP/docker-builds/issues/13
