### ISSUE TITLE
Add war file to the docker image

### ISSUE THREAD

**Issue by maina** [OpenSRP/docker-builds#6]
Based on this thread seems we need to include the server war file as part of the docker image to simplify setup process
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/opensrp-dev/IOrB62mFVfE
- [ ] automate war build process in travis to publish versioned war files to s3
- [ ] add war file to be part of the docker image
- [ ] publish image to docker-hub
- [ ] test if the image works in mac and ubuntu environments

**Comment by cagulas** [comment]
No longer relevant, closing.
