### ISSUE TITLE
Wrong opensrp_openmrs_modules download link

### ISSUE THREAD

**Issue by baksosapi** [OpenSRP/docker-builds#7]
Failed to extract on link http://netcologne.dl.sourceforge.net/project/keymane/opensrp/opensrp_openmrs_modules.tar.gz

``` 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by keymane** [comment]
I've been able to download and extract the modules. It's probably a network issue

**Comment by baksosapi** [comment]
Maybe how if it move to other site?. If this networks issue I think it based on location where user access the links, cause sourceforge is based on their mirror. I don't know if there is restriction from accessing the sorceforge mirror link from specific location/country.

**Comment by mib-iqbal** [comment]
`curl -i http://netcologne.dl.sourceforge.net/project/keymane/opensrp/opensrp_openmrs_modules.tar.gz
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.13.6
Date: Wed, 08 Nov 2017 11:39:44 GMT
Content-Type: text/html
Location: http://downloads.sourceforge.net/project/keymane/opensrp/opensrp_openmrs_modules.tar.gz?download&failedmirror=netcologne.dl.sourceforge.net
Content-Length: 161
Connection: Keep-Alive

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.13.6</center>
</body>
</html>
`

**Comment by keymane** [comment]
Fixed in  https://github.com/OpenSRP/docker-builds/issues/12
